In [1]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
base_plano_saude2 = pd.read_csv('Bases de dados\plano_saude2.csv')
X_plano_saude2 = base_plano_saude2.iloc[:, 0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:, 1].values

In [6]:
# Kernel Linear
from sklearn.svm import SVR
regressor_svr_saude_linear = SVR(kernel='linear')
regressor_svr_saude_linear.fit(X_plano_saude2, y_plano_saude2)



SVR(kernel='linear')

In [7]:
grafico=px.scatter(x=X_plano_saude2.ravel(), y=y_plano_saude2)
grafico.add_scatter(x=X_plano_saude2.ravel(), y=regressor_svr_saude_linear.predict(X_plano_saude2), name = 'Regressao')
grafico.show()

In [10]:
# Kernel Polinomial
regressor_svr_saude_poly = SVR(kernel='poly', degree=4)
regressor_svr_saude_poly.fit(X_plano_saude2, y_plano_saude2)


SVR(degree=4, kernel='poly')

In [11]:
grafico=px.scatter(x=X_plano_saude2.ravel(), y=y_plano_saude2)
grafico.add_scatter(x=X_plano_saude2.ravel(), y=regressor_svr_saude_poly.predict(X_plano_saude2), name = 'Regressao')
grafico.show()

In [28]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X_plano_saude2_scaled = scaler_x.fit_transform(X_plano_saude2)
scaler_y = StandardScaler()
y_plano_saude2_scaled = scaler_y.fit_transform(y_plano_saude2.reshape(-1,1))

In [29]:
X_plano_saude2_scaled

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [30]:
y_plano_saude2_scaled

array([[-0.72401136],
       [-0.7065653 ],
       [-0.66818397],
       [-0.59839975],
       [-0.48674498],
       [-0.35415495],
       [-0.17620517],
       [ 0.18667281],
       [ 0.8914935 ],
       [ 2.63609918]])

In [31]:
#Kernel rbf
regressor_svr_saude_rbf = SVR(kernel='rbf')
regressor_svr_saude_rbf.fit(X_plano_saude2_scaled, y_plano_saude2_scaled.ravel())

SVR()

In [32]:
grafico=px.scatter(x=X_plano_saude2_scaled.ravel(), y=y_plano_saude2_scaled.ravel())
grafico.add_scatter(x=X_plano_saude2_scaled.ravel(), y=regressor_svr_saude_rbf.predict(X_plano_saude2_scaled), name = 'Regressao')
grafico.show()

In [41]:
novo=[[40]]
novo = scaler_x.transform(novo)

In [42]:
regressor_svr_saude_rbf.predict(novo)

array([-0.42259356])

In [ ]:
scaler_y.inverse_transform(regressor_svr_saude_rbf.predict(novo))

In [49]:
import numpy as np

# Supondo que você já tenha definido os objetos scaler_x e regressor_svr_saude_rbf

# Criar um novo exemplo bidimensional
novo = np.array([[40]])

# Padronizar o novo exemplo
novo_padronizado = scaler_x.transform(novo)

# Realizar a previsão usando o modelo treinado
previsao_padronizada = regressor_svr_saude_rbf.predict(novo_padronizado.reshape(1, -1))

# Inverter a transformação para obter a previsão original na escala original
previsao_original = scaler_y.inverse_transform(previsao_padronizada.reshape(-1, 1))

# Exibir a previsão original
print(previsao_original)


[[1333.85650748]]
