In [1]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

Base Plano Saude

In [2]:
base_plano_saude2 = pd.read_csv('Bases de dados\plano_saude2.csv')

In [3]:
X_plano_saude2 = base_plano_saude2.iloc[:, 0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:, 1].values

In [8]:
print('dados X_plano_saude: {}'.format(X_plano_saude2))
print('dados y_plano_saude: {}'.format(y_plano_saude2))

dados X_plano_saude: [[18]
 [23]
 [28]
 [33]
 [38]
 [43]
 [48]
 [53]
 [58]
 [63]]
dados y_plano_saude: [  470   520   630   830  1150  1530  2040  3080  5100 10100]


In [36]:
from sklearn.ensemble import RandomForestRegressor
regressor_random_forest_saude = RandomForestRegressor(n_estimators=100)
regressor_random_forest_saude.fit(X_plano_saude2, y_plano_saude2)

RandomForestRegressor()

In [37]:
regressor_random_forest_saude.score(X_plano_saude2, y_plano_saude2)

0.9698653616311523

In [38]:
import numpy as np 
X_teste_arvore= np.arange(min(X_plano_saude2), max(X_plano_saude2), 0.1)
X_teste_arvore = X_teste_arvore.reshape(-1,1)
X_teste_arvore.shape


C:\Users\diego\AppData\Local\Temp\ipykernel_15712\785927710.py:2: DeprecationWarning:

Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)



(450, 1)

In [39]:
grafico=px.scatter(x=X_plano_saude2.ravel(), y=y_plano_saude2)
grafico.add_scatter(x=X_teste_arvore.ravel(), y=regressor_random_forest_saude.predict(X_teste_arvore), name = 'Regressao')
grafico.show()

In [40]:
regressor_random_forest_saude.predict([[40]])

array([1277.1])

Base preco da casas

In [23]:
base_casas = pd.read_csv('Bases de dados\house_prices.csv')


In [24]:
X_casas = base_casas.iloc[:, 3:19].values
y_casas = base_casas.iloc[:, 2].values

In [32]:
from sklearn.model_selection import train_test_split
X_casas_treinamento, X_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(
    X_casas, y_casas, test_size=0.3, random_state=0
)

In [34]:
X_casas_treinamento

array([[ 4.00000e+00,  1.50000e+00,  1.39000e+03, ...,  9.81330e+04,
         4.77224e+01, -1.22332e+02],
       [ 3.00000e+00,  1.50000e+00,  1.45000e+03, ...,  9.81330e+04,
         4.77725e+01, -1.22349e+02],
       [ 5.00000e+00,  2.75000e+00,  2.86000e+03, ...,  9.80520e+04,
         4.77082e+01, -1.22104e+02],
       ...,
       [ 3.00000e+00,  2.25000e+00,  2.36000e+03, ...,  9.80420e+04,
         4.73856e+01, -1.22158e+02],
       [ 4.00000e+00,  2.00000e+00,  2.37000e+03, ...,  9.80010e+04,
         4.72831e+01, -1.22279e+02],
       [ 4.00000e+00,  2.25000e+00,  2.38000e+03, ...,  9.80080e+04,
         4.76126e+01, -1.22120e+02]])

In [33]:
y_casas_treinamento

array([400000., 430000., 720000., ..., 431000., 411000., 699900.])

In [35]:
X_casas_teste

array([[ 2.00000e+00,  1.50000e+00,  1.43000e+03, ...,  9.81250e+04,
         4.77222e+01, -1.22290e+02],
       [ 4.00000e+00,  3.25000e+00,  4.67000e+03, ...,  9.80050e+04,
         4.76350e+01, -1.22164e+02],
       [ 2.00000e+00,  7.50000e-01,  1.44000e+03, ...,  9.81070e+04,
         4.76707e+01, -1.22364e+02],
       ...,
       [ 3.00000e+00,  2.50000e+00,  2.15000e+03, ...,  9.80580e+04,
         4.74514e+01, -1.22089e+02],
       [ 3.00000e+00,  1.75000e+00,  1.48000e+03, ...,  9.80320e+04,
         4.73657e+01, -1.22280e+02],
       [ 3.00000e+00,  1.00000e+00,  1.32000e+03, ...,  9.80920e+04,
         4.73120e+01, -1.22183e+02]])

In [41]:
regressor_random_forest_casas = RandomForestRegressor(n_estimators=100)
regressor_random_forest_casas.fit(X_casas_treinamento, y_casas_treinamento)

RandomForestRegressor()

In [42]:
regressor_random_forest_casas.score(X_casas_treinamento, y_casas_treinamento)

0.9814221179501458

In [43]:
regressor_random_forest_casas.score(X_casas_teste, y_casas_teste)

0.8814258224975635

In [44]:
previsoes = regressor_random_forest_casas.predict(X_casas_teste)
previsoes

array([ 300583.5 , 1746946.7 ,  541288.  , ...,  365523.76,  230815.5 ,
        205691.73])

In [45]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [46]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_casas_teste, previsoes)

67827.17642822748